### ISSUE TITLE
</pre> and </blockquote> after accessibility rule syntax are interpreted wrong in unsorted.md

### ISSUE THREAD

**Issue by nortti0** [Xkeeper0/emotracker-documentation#1]
For some reason (I do not really know about github pages), the `</pre>` and `</blockquote>` elements after the block containing BNF for the accessibility rules are not interpreted as HTML and instead end up visible on the page. This causes rest of the page to appear as preformatted fixed width text inside a block quote.

Conversely, `<any character>` gets interpreted as an HTML tag and becomes `<any character="">` in the resulting HTML page.

**Comment by Xkeeper0** [comment]
vs code's preview lied to me but the good news is that this is now fixed
